- name: nginx installation
  hosts: frontend
  become: yes
  tasks:
    -name: nginx install
    ansible.builtin.package:
      name: nginx
      state: present

    -name: nginx run
    ansible.builtin.service:
      name: nginx
      state: started
      enable: yes