- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Raheem,Joseph"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course Info: {{ course | dict2items  }}"

  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'trainer', 'value': 'John'}
    ansible.builtin.debug:
      msg: "Course Info: {{ course | items2dict  }}"

  - name: convert to uppercase
    vars:
      name: "Sri vishnu sai B"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: convert to lowercase
    vars:
      name: "sRI VISHNU SAI b"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: check IP address is valid or not
    vars:
      ip: "192.168.1.1"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"