Name: Install Nginx
hosts: dynamic_frontend
become: yes
serial: 5
tasks:
- name: install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
  
- name: run nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
