Name: Install Nginx
hosts: frontend
become: yes
tasks:
  name: install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
  
  name: run nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
