[frontend]
172.31.41.22 COURSE=Ansible DURATION=10HR TRAINER=Sivakumar ansible_user=ec2-user ansible_password=DevOps321
172.31.42.49 COURSE=variables DURATION=1.5HR TRAINER=Sivakumar ansible_user=ec2-user ansible_password=DevOps321

[local]
localhost

[local:vars]
COURSE=DevOps with AWS
Intructor=John
DURATION=1.5 HR

